//! Regression test for a class-file forwarder beside its generic pickle copy.
//!
//! A module class generated by scalac carries a raw JVM forwarder for a
//! default method inherited from a trait.  Loading the trait's ScalaSignature
//! then adds the generic declaration on the same module.  The intermediate
//! trait hierarchy can also leave the original declaration in the lookup set;
//! all three describe one member and must not become an ambiguous overload.
//!
//! The fixture has a second, same-arity `Int` overload so the collapse is
//! required to distinguish a genuine overload from the duplicate pair.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

fn bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_scala-rs"))
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures")
}

fn scala_library_jar() -> Option<PathBuf> {
    let jar = PathBuf::from("/tmp/scala-rs-lib/scala-library-2.13.16.jar");
    jar.is_file().then_some(jar)
}

fn scalac() -> Option<PathBuf> {
    let cached = PathBuf::from("/tmp/scala-2.13.16/bin/scalac");
    if cached.is_file() {
        return Some(cached);
    }
    Command::new("scalac")
        .arg("-version")
        .output()
        .ok()
        .filter(|output| output.status.success() || !output.stderr.is_empty())
        .map(|_| PathBuf::from("scalac"))
}

fn java_available() -> bool {
    Command::new("java")
        .arg("-version")
        .output()
        .map(|output| output.status.success() || !output.stderr.is_empty())
        .unwrap_or(false)
}

fn temp_dir() -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or(0);
    let path = std::env::temp_dir().join(format!(
        "scala-rs-dbconfigforurl-{}-{nanos}",
        std::process::id()
    ));
    fs::create_dir_all(&path).unwrap();
    path
}

fn diagnostics(output: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

fn compile_reader(source: &Path, out: &Path, cp: &str, library: &Path) -> Output {
    Command::new(bin())
        .args([
            "compile",
            source.to_str().unwrap(),
            "-cp",
            cp,
            "--scala-library",
            library.to_str().unwrap(),
            "-d",
            out.to_str().unwrap(),
        ])
        .output()
        .expect("run scala-rs compile")
}

#[test]
fn classfile_forwarder_and_generic_pickle_are_one_forurl_overload() {
    if !java_available() {
        eprintln!("skip DatabaseConfig.forURL regression: java unavailable");
        return;
    }
    let Some(scalac) = scalac() else {
        eprintln!("skip DatabaseConfig.forURL regression: scalac unavailable");
        return;
    };
    let Some(library) = scala_library_jar() else {
        eprintln!("skip DatabaseConfig.forURL regression: scala-library jar unavailable");
        return;
    };

    let root = temp_dir();
    let writer = root.join("writer");
    let reader = root.join("reader");
    fs::create_dir_all(&writer).unwrap();
    fs::create_dir_all(&reader).unwrap();

    let lib = Command::new(&scalac)
        .args([
            "-d",
            writer.to_str().unwrap(),
            fixtures_dir()
                .join("dbconfig_forurl_lib.scala")
                .to_str()
                .unwrap(),
            fixtures_dir()
                .join("missing_config.scala")
                .to_str()
                .unwrap(),
        ])
        .output()
        .expect("run scalac writer");
    assert!(
        lib.status.success(),
        "scalac writer failed:\n{}",
        diagnostics(&lib)
    );

    let jar = root.join("dbconfig-forurl-lib.jar");
    let packed = Command::new("jar")
        .args([
            "cf",
            jar.to_str().unwrap(),
            "-C",
            writer.to_str().unwrap(),
            "dbconfig",
        ])
        .output()
        .expect("pack classfile/pickle fixture");
    assert!(
        packed.status.success(),
        "jar failed:\n{}",
        diagnostics(&packed)
    );

    let cp = format!("{}:{}", jar.display(), library.display());
    let use_stage = compile_reader(
        &fixtures_dir().join("dbconfig_forurl_use.scala"),
        &reader,
        &cp,
        &library,
    );
    assert!(
        use_stage.status.success(),
        "scala-rs reader failed:\n{}",
        diagnostics(&use_stage)
    );

    // `missing.Config` is deliberately absent from the reader classpath: this
    // leaves the eager trait symbol with an unknown erasure, as Slick's
    // `com.typesafe.config.Config` does.  The JVM still gets the class at run
    // time so verifier/linkage checks exercise the emitted descriptors.
    let runtime_cp = format!("{}:{}:{}", reader.display(), cp, writer.display());
    let run = Command::new("java")
        .args(["-Xverify:all", "-cp", &runtime_cp, "DbConfigForUrlUse"])
        .output()
        .expect("run DatabaseConfig.forURL fixture");
    assert!(
        run.status.success(),
        "java -Xverify:all failed:\n{}",
        diagnostics(&run)
    );
    assert_eq!(
        String::from_utf8_lossy(&run.stdout),
        "1\n2\n",
        "the genuine Int overload was not preserved"
    );

    let _ = fs::remove_dir_all(root);
}
