// Regenerate crates/pickle/src/java_identifier_parts.rs with JDK 17.
// Scala 2.13 NameTransformer classifies UTF-16 chars with this Java API.
public final class GenerateJavaIdentifierParts {
    public static void main(String[] args) {
        if (Runtime.version().feature() != 17) {
            throw new IllegalStateException("Use the pinned JDK 17 (Unicode 13.0)");
        }
        System.out.println("// Generated by tests/tools/GenerateJavaIdentifierParts.java with JDK 17.");
        System.out.println("// Unicode 13.0 BMP ranges for Character.isJavaIdentifierPart(char).");
        System.out.println("pub(super) const JAVA_IDENTIFIER_PARTS: &[(u16, u16)] = &[");
        int start = -1;
        for (int c = 0; c <= 0x10000; c++) {
            boolean ok = c < 0x10000 && Character.isJavaIdentifierPart((char)c);
            if (ok && start < 0) start = c;
            if (!ok && start >= 0) {
                System.out.printf("    (0x%04X, 0x%04X),%n", start, c - 1);
                start = -1;
            }
        }
        System.out.println("];");
    }
}
