// Regenerate crates/lexer/src/unicode_symbols.rs with JDK 17:
//   java tests/tools/GenerateUnicodeSymbols.java > crates/lexer/src/unicode_symbols.rs
// Scala 2.13's scanner (`Chars.isSpecial`) makes a code point an operator
// character when Java classifies it MATH_SYMBOL (Sm) or OTHER_SYMBOL (So).
public final class GenerateUnicodeSymbols {
    public static void main(String[] args) {
        if (Runtime.version().feature() != 17) {
            throw new IllegalStateException("Use the pinned JDK 17 (Unicode 13.0)");
        }
        System.out.println("// Generated by tests/tools/GenerateUnicodeSymbols.java with JDK 17.");
        System.out.println("// Unicode 13.0 code point ranges whose Character.getType is");
        System.out.println("// MATH_SYMBOL or OTHER_SYMBOL (nsc `Chars.isSpecial`).");
        System.out.println("pub(crate) const SYMBOL_RANGES: &[(u32, u32)] = &[");
        int start = -1;
        for (int c = 0; c <= Character.MAX_CODE_POINT + 1; c++) {
            boolean ok = false;
            if (c <= Character.MAX_CODE_POINT) {
                int t = Character.getType(c);
                ok = t == Character.MATH_SYMBOL || t == Character.OTHER_SYMBOL;
            }
            if (ok && start < 0) start = c;
            if (!ok && start >= 0) {
                System.out.printf("    (0x%04X, 0x%04X),%n", start, c - 1);
                start = -1;
            }
        }
        System.out.println("];");
    }
}
