// Regenerate crates/pickle/src/java_identifier_parts.rs with the pinned JDK.
// Scala 2.13 NameTransformer classifies UTF-16 chars with this Java API.
public final class GenerateJavaIdentifierParts {
    public static void main(String[] args) {
        int feature = Runtime.version().feature();
        if (feature != 17 && feature != 21) {
            throw new IllegalStateException("Use the pinned JDK 17 or 21");
        }
        System.out.printf("// Generated by tests/tools/GenerateJavaIdentifierParts.java with JDK %d.%n", feature);
        System.out.println("// BMP ranges for Character.isJavaIdentifierPart(char) on the pinned JDK.");
        System.out.println("pub(super) const JAVA_IDENTIFIER_PARTS: &[(u16, u16)] = &[");
        int start = -1;
        for (int c = 0; c <= 0x10000; c++) {
            boolean ok = c < 0x10000 && Character.isJavaIdentifierPart((char)c);
            if (ok && start < 0) start = c;
            if (!ok && start >= 0) {
                System.out.printf("    (0x%04X, 0x%04X),%n", start, c - 1);
                start = -1;
            }
        }
        System.out.println("];");
    }
}
