//! Full reader for the nsc 2.13 `ScalaSignature` pickle format.
//!
//! `pickle.rs` is the *writer* (a subset of nsc `PickleFormat`) plus a small
//! ad-hoc unpickler that only recovers what scala-rs itself emits. This module
//! is the complement: a **complete** reader for the format as produced by
//! scalac 2.13, able to parse every entry of every `.class` in
//! `scala-library-2.13.16.jar`.
//!
//! Layout (nsc `PickleBuffer` / `UnPickler`):
//!
//! ```text
//! pickle  = majorVersion_Nat minorVersion_Nat nentries_Nat { Entry }
//! Entry   = tag_Nat len_Nat [len bytes]
//! ```
//!
//! All references between entries are entry indices written as `Nat`
//! (big-endian base-128). Every entry body is parsed to the byte, and the
//! reader *fails* (rather than silently skipping) when a tag is unknown, when
//! a body is malformed, or when a body is not consumed exactly — that
//! exactness check is what makes this reader a useful regression test against
//! the real standard library.

use std::fmt;

// ---------------------------------------------------------------------------
// Tag table (scala/reflect/internal/pickling/PickleFormat.scala)
// ---------------------------------------------------------------------------

/// nsc `PickleFormat` tags. Names match the Scala source (mixed case included)
/// so the table can be diffed against `PickleFormat.scala` by eye.
#[allow(non_upper_case_globals)]
pub mod tags {
    pub const TERMname: u8 = 1;
    pub const TYPEname: u8 = 2;
    pub const NONEsym: u8 = 3;
    pub const TYPEsym: u8 = 4;
    pub const ALIASsym: u8 = 5;
    pub const CLASSsym: u8 = 6;
    pub const MODULEsym: u8 = 7;
    pub const VALsym: u8 = 8;
    pub const EXTref: u8 = 9;
    pub const EXTMODCLASSref: u8 = 10;
    pub const NOtpe: u8 = 11;
    pub const NOPREFIXtpe: u8 = 12;
    pub const THIStpe: u8 = 13;
    pub const SINGLEtpe: u8 = 14;
    pub const CONSTANTtpe: u8 = 15;
    pub const TYPEREFtpe: u8 = 16;
    pub const TYPEBOUNDStpe: u8 = 17;
    pub const REFINEDtpe: u8 = 18;
    pub const CLASSINFOtpe: u8 = 19;
    pub const METHODtpe: u8 = 20;
    pub const POLYtpe: u8 = 21;
    /// No longer generated by 2.13 scalac, but still readable.
    pub const IMPLICITMETHODtpe: u8 = 22;

    pub const LITERAL: u8 = 23;
    pub const LITERALunit: u8 = 24;
    pub const LITERALboolean: u8 = 25;
    pub const LITERALbyte: u8 = 26;
    pub const LITERALshort: u8 = 27;
    pub const LITERALchar: u8 = 28;
    pub const LITERALint: u8 = 29;
    pub const LITERALlong: u8 = 30;
    pub const LITERALfloat: u8 = 31;
    pub const LITERALdouble: u8 = 32;
    pub const LITERALstring: u8 = 33;
    pub const LITERALnull: u8 = 34;
    pub const LITERALclass: u8 = 35;
    pub const LITERALenum: u8 = 36;
    /// `scala.Symbol` literals; dropped from the language, still a valid tag.
    pub const LITERALsymbol: u8 = 37;

    pub const SYMANNOT: u8 = 40;
    pub const CHILDREN: u8 = 41;
    pub const ANNOTATEDtpe: u8 = 42;
    pub const ANNOTINFO: u8 = 43;
    pub const ANNOTARGARRAY: u8 = 44;

    pub const SUPERtpe: u8 = 46;
    /// No longer generated by 2.13 scalac, but still readable.
    pub const DEBRUIJNINDEXtpe: u8 = 47;
    pub const EXISTENTIALtpe: u8 = 48;
    /// Prefix tag: the entry body is a pickled tree.
    pub const TREE: u8 = 49;
    pub const MODIFIERS: u8 = 50;

    // Tree tags (the first byte of a TREE entry body).
    pub const EMPTYtree: u8 = 1;
    pub const PACKAGEtree: u8 = 2;
    pub const CLASStree: u8 = 3;
    pub const MODULEtree: u8 = 4;
    pub const VALDEFtree: u8 = 5;
    pub const DEFDEFtree: u8 = 6;
    pub const TYPEDEFtree: u8 = 7;
    pub const LABELtree: u8 = 8;
    pub const IMPORTtree: u8 = 9;
    pub const DOCDEFtree: u8 = 11;
    pub const TEMPLATEtree: u8 = 12;
    pub const BLOCKtree: u8 = 13;
    pub const CASEtree: u8 = 14;
    pub const ALTERNATIVEtree: u8 = 16;
    pub const STARtree: u8 = 17;
    pub const BINDtree: u8 = 18;
    pub const UNAPPLYtree: u8 = 19;
    pub const ARRAYVALUEtree: u8 = 20;
    pub const FUNCTIONtree: u8 = 21;
    pub const ASSIGNtree: u8 = 22;
    pub const IFtree: u8 = 23;
    pub const MATCHtree: u8 = 24;
    pub const RETURNtree: u8 = 25;
    pub const TREtree: u8 = 26;
    pub const THROWtree: u8 = 27;
    pub const NEWtree: u8 = 28;
    pub const TYPEDtree: u8 = 29;
    pub const TYPEAPPLYtree: u8 = 30;
    pub const APPLYtree: u8 = 31;
    pub const APPLYDYNAMICtree: u8 = 32;
    pub const SUPERtree: u8 = 33;
    pub const THIStree: u8 = 34;
    pub const SELECTtree: u8 = 35;
    pub const IDENTtree: u8 = 36;
    pub const LITERALtree: u8 = 37;
    pub const TYPEtree: u8 = 38;
    pub const ANNOTATEDtree: u8 = 39;
    pub const SINGLETONTYPEtree: u8 = 40;
    pub const SELECTFROMTYPEtree: u8 = 41;
    pub const COMPOUNDTYPEtree: u8 = 42;
    pub const APPLIEDTYPEtree: u8 = 43;
    pub const TYPEBOUNDStree: u8 = 44;
    pub const EXISTENTIALTYPEtree: u8 = 45;

    pub const FIRST_SYM_TAG: u8 = NONEsym;
    pub const LAST_SYM_TAG: u8 = VALsym;
    pub const LAST_EXT_SYM_TAG: u8 = EXTMODCLASSref;
}

// ---------------------------------------------------------------------------
// Pickled flags (scala/reflect/internal/Flags.scala, pickled positions)
// ---------------------------------------------------------------------------

/// Pickled flag bits, i.e. the bits as they appear in a symbol's `flags_LongNat`
/// *before* `pickledToRawFlags`. nsc pickles the "raw" long with the late/anti
/// bits shifted; the low 32 bits below are position-stable across the mapping.
#[allow(non_upper_case_globals)]
pub mod pflags {
    pub const IMPLICIT: u64 = 1 << 0;
    pub const FINAL: u64 = 1 << 1;
    pub const PRIVATE: u64 = 1 << 2;
    pub const PROTECTED: u64 = 1 << 3;
    pub const SEALED: u64 = 1 << 4;
    pub const OVERRIDE: u64 = 1 << 5;
    pub const CASE: u64 = 1 << 6;
    pub const ABSTRACT: u64 = 1 << 7;
    pub const DEFERRED: u64 = 1 << 8;
    pub const METHOD: u64 = 1 << 9;
    pub const MODULE: u64 = 1 << 10;
    pub const INTERFACE: u64 = 1 << 11;
    pub const MUTABLE: u64 = 1 << 12;
    pub const PARAM: u64 = 1 << 13;
    pub const PACKAGE: u64 = 1 << 14;
    pub const MACRO: u64 = 1 << 15;
    pub const COVARIANT: u64 = 1 << 16;
    pub const BYNAMEPARAM: u64 = 1 << 17;
    pub const CONTRAVARIANT: u64 = 1 << 18;
    pub const ABSOVERRIDE: u64 = 1 << 19;
    pub const LOCAL: u64 = 1 << 20;
    pub const JAVA: u64 = 1 << 21;
    pub const SYNTHETIC: u64 = 1 << 22;
    pub const STABLE: u64 = 1 << 23;
    pub const STATIC: u64 = 1 << 24;
    pub const CASEACCESSOR: u64 = 1 << 25;
    pub const DEFAULTPARAM: u64 = 1 << 26;
    pub const TRAIT: u64 = 1 << 27;
    pub const BRIDGE: u64 = 1 << 28;
    pub const ACCESSOR: u64 = 1 << 29;
    pub const SUPERACCESSOR: u64 = 1 << 30;
    pub const PARAMACCESSOR: u64 = 1 << 31;
    pub const MODULEVAR: u64 = 1 << 32;
    pub const LAZY: u64 = 1 << 33;
    pub const IS_ERROR: u64 = 1 << 34;
    pub const OVERLOADED: u64 = 1 << 35;
    pub const LIFTED: u64 = 1 << 36;
    pub const EXISTENTIAL: u64 = 1 << 37;
    pub const EXPANDEDNAME: u64 = 1 << 38;
    pub const IMPLCLASS: u64 = 1 << 39;
    pub const PRESUPER: u64 = 1 << 40;
    pub const TRANS_FLAG: u64 = 1 << 41;
    pub const LOCKED: u64 = 1 << 42;
    pub const SPECIALIZED: u64 = 1 << 43;
    pub const DEFAULTINIT: u64 = 1 << 44;
    pub const VBRIDGE: u64 = 1 << 45;
    pub const VARARGS: u64 = 1 << 46;
    pub const TRIEDCOOKING: u64 = 1 << 47;
    pub const SYNCHRONIZED: u64 = 1 << 48;
    pub const ARTIFACT: u64 = 1 << 49;
    pub const JAVA_DEFAULTMETHOD: u64 = 1 << 50;
    pub const ENUM: u64 = 1 << 51;
    pub const JAVA_ANNOTATION: u64 = 1 << 52;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// A pickle that could not be read, pinpointed to the offending entry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReadError {
    /// Index of the entry being parsed (`usize::MAX` for the header).
    pub entry: usize,
    /// Tag byte of the entry being parsed (0 for the header).
    pub tag: u8,
    /// Byte offset within the pickle where the failure was detected.
    pub offset: usize,
    pub message: String,
}

impl fmt::Display for ReadError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.entry == usize::MAX {
            write!(f, "pickle header at {}: {}", self.offset, self.message)
        } else {
            write!(
                f,
                "entry #{} (tag {}) at byte {}: {}",
                self.entry, self.tag, self.offset, self.message
            )
        }
    }
}

type Result<T> = std::result::Result<T, ReadError>;

/// Entry index (a pickle-internal reference).
pub type Idx = u32;

// ---------------------------------------------------------------------------
// Entries
// ---------------------------------------------------------------------------

/// The `name owner flags [privateWithin] info` prefix shared by all
/// non-external symbol entries (nsc `Pickler.writeSymInfo`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SymInfo {
    pub name: Idx,
    pub owner: Idx,
    /// Raw pickled flags (nsc `rawToPickledFlags` output); see [`pflags`].
    pub flags: u64,
    pub private_within: Option<Idx>,
    pub info: Idx,
}

impl SymInfo {
    pub fn has(&self, flag: u64) -> bool {
        self.flags & flag != 0
    }
}

/// A pickled `Constant`.
#[derive(Clone, Debug, PartialEq)]
pub enum Constant {
    Unit,
    Boolean(bool),
    Byte(i8),
    Short(i16),
    Char(u32),
    Int(i32),
    Long(i64),
    Float(f32),
    Double(f64),
    /// Reference to the `TERMname` entry holding the string.
    Str(Idx),
    Null,
    /// `classOf[T]`: reference to the type entry.
    Class(Idx),
    /// Java enum constant: reference to the symbol entry.
    Enum(Idx),
    /// `'sym` literal (pre-2.13 pickles): reference to the name entry.
    Symbol(Idx),
}

/// A pickled `AnnotationInfo` body: `info_Ref {annotArg_Ref} {name_Ref annotArg_Ref}`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnnotInfo {
    pub tpe: Idx,
    pub args: Vec<Idx>,
    pub assocs: Vec<(Idx, Idx)>,
}

/// One `{from, to}` pair of an `Import` selector list.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImportSelector {
    pub from: Idx,
    pub to: Idx,
}

/// A pickled tree (only annotation arguments and `DocDef`s reach here in
/// practice, but every `PickleFormat` tree tag is covered).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Tree {
    Empty,
    PackageDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        pid: Idx,
        stats: Vec<Idx>,
    },
    ClassDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        template: Idx,
        tparams: Vec<Idx>,
    },
    ModuleDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        template: Idx,
    },
    ValDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        tpt: Idx,
        rhs: Idx,
    },
    DefDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        tparams: Vec<Idx>,
        vparamss: Vec<Vec<Idx>>,
        tpt: Idx,
        rhs: Idx,
    },
    TypeDef {
        sym: Idx,
        mods: Idx,
        name: Idx,
        rhs: Idx,
        tparams: Vec<Idx>,
    },
    LabelDef {
        sym: Idx,
        name: Idx,
        rhs: Idx,
        params: Vec<Idx>,
    },
    Import {
        sym: Idx,
        expr: Idx,
        selectors: Vec<ImportSelector>,
    },
    DocDef {
        comment: Idx,
        definition: Idx,
    },
    Template {
        sym: Idx,
        parents: Vec<Idx>,
        self_: Idx,
        body: Vec<Idx>,
    },
    Block {
        expr: Idx,
        stats: Vec<Idx>,
    },
    CaseDef {
        pat: Idx,
        guard: Idx,
        body: Idx,
    },
    Alternative(Vec<Idx>),
    Star(Idx),
    Bind {
        sym: Idx,
        name: Idx,
        body: Idx,
    },
    UnApply {
        fun: Idx,
        args: Vec<Idx>,
    },
    ArrayValue {
        elemtpt: Idx,
        elems: Vec<Idx>,
    },
    Function {
        sym: Idx,
        body: Idx,
        vparams: Vec<Idx>,
    },
    Assign {
        lhs: Idx,
        rhs: Idx,
    },
    If {
        cond: Idx,
        thenp: Idx,
        elsep: Idx,
    },
    Match {
        selector: Idx,
        cases: Vec<Idx>,
    },
    Return {
        sym: Idx,
        expr: Idx,
    },
    Try {
        block: Idx,
        finalizer: Idx,
        catches: Vec<Idx>,
    },
    Throw(Idx),
    New(Idx),
    Typed {
        expr: Idx,
        tpt: Idx,
    },
    TypeApply {
        fun: Idx,
        args: Vec<Idx>,
    },
    Apply {
        fun: Idx,
        args: Vec<Idx>,
    },
    ApplyDynamic {
        sym: Idx,
        fun: Idx,
        args: Vec<Idx>,
    },
    Super {
        sym: Idx,
        qual: Idx,
        mix: Idx,
    },
    This {
        sym: Idx,
        qual: Idx,
    },
    Select {
        sym: Idx,
        qualifier: Idx,
        selector: Idx,
    },
    Ident {
        sym: Idx,
        name: Idx,
    },
    Literal(Idx),
    TypeTree,
    Annotated {
        annot: Idx,
        arg: Idx,
    },
    SingletonTypeTree(Idx),
    SelectFromTypeTree {
        qualifier: Idx,
        selector: Idx,
    },
    CompoundTypeTree(Idx),
    AppliedTypeTree {
        tpt: Idx,
        args: Vec<Idx>,
    },
    TypeBoundsTree {
        lo: Idx,
        hi: Idx,
    },
    ExistentialTypeTree {
        tpt: Idx,
        where_clauses: Vec<Idx>,
    },
}

/// One entry of the pickle's entry table.
#[derive(Clone, Debug, PartialEq)]
pub enum Entry {
    TermName(String),
    TypeName(String),
    NoneSym,
    TypeSym(SymInfo),
    AliasSym(SymInfo),
    ClassSym {
        info: SymInfo,
        /// `typeOfThis` when the class has a self type.
        this_type: Option<Idx>,
    },
    ModuleSym {
        info: SymInfo,
        alias: Option<Idx>,
    },
    ValSym {
        info: SymInfo,
        alias: Option<Idx>,
    },
    ExtRef {
        name: Idx,
        owner: Option<Idx>,
    },
    ExtModClassRef {
        name: Idx,
        owner: Option<Idx>,
    },
    NoTpe,
    NoPrefixTpe,
    ThisTpe(Idx),
    SingleTpe {
        prefix: Idx,
        sym: Idx,
    },
    SuperTpe {
        this_tpe: Idx,
        super_tpe: Idx,
    },
    ConstantTpe(Idx),
    TypeRefTpe {
        prefix: Idx,
        sym: Idx,
        args: Vec<Idx>,
    },
    TypeBoundsTpe {
        lo: Idx,
        hi: Idx,
    },
    RefinedTpe {
        sym: Idx,
        parents: Vec<Idx>,
    },
    ClassInfoTpe {
        sym: Idx,
        parents: Vec<Idx>,
    },
    MethodTpe {
        result: Idx,
        params: Vec<Idx>,
    },
    /// nsc `IMPLICITMETHODtpe`; no longer written, treated like `MethodTpe`.
    ImplicitMethodTpe {
        result: Idx,
        params: Vec<Idx>,
    },
    PolyTpe {
        result: Idx,
        tparams: Vec<Idx>,
    },
    ExistentialTpe {
        result: Idx,
        quantified: Vec<Idx>,
    },
    AnnotatedTpe {
        tpe: Idx,
        annots: Vec<Idx>,
    },
    /// nsc `DEBRUIJNINDEXtpe`; no longer written.
    DeBruijnIndexTpe {
        level: u32,
        index: u32,
    },
    Literal(Constant),
    SymAnnot {
        sym: Idx,
        annot: AnnotInfo,
    },
    AnnotInfo(AnnotInfo),
    AnnotArgArray(Vec<Idx>),
    Children {
        sym: Idx,
        children: Vec<Idx>,
    },
    Tree {
        tpe: Option<Idx>,
        tree: Tree,
    },
    Modifiers {
        flags: u64,
        private_within: Idx,
    },
}

impl Entry {
    /// The `SymInfo` of any non-external symbol entry.
    pub fn sym_info(&self) -> Option<&SymInfo> {
        match self {
            Entry::TypeSym(i)
            | Entry::AliasSym(i)
            | Entry::ClassSym { info: i, .. }
            | Entry::ModuleSym { info: i, .. }
            | Entry::ValSym { info: i, .. } => Some(i),
            _ => None,
        }
    }
}

/// A fully parsed pickle.
#[derive(Clone, Debug)]
pub struct Pickle {
    pub major: u32,
    pub minor: u32,
    pub entries: Vec<Entry>,
    /// Tag byte of each entry, in table order.
    pub entry_tags: Vec<u8>,
}

impl Pickle {
    pub fn entry(&self, i: Idx) -> Option<&Entry> {
        self.entries.get(i as usize)
    }

    /// Text of a `TERMname` / `TYPEname` entry.
    pub fn name(&self, i: Idx) -> Option<&str> {
        match self.entries.get(i as usize)? {
            Entry::TermName(s) | Entry::TypeName(s) => Some(s.as_str()),
            _ => None,
        }
    }

    /// The name entry of a symbol (internal or external).
    pub fn sym_name(&self, i: Idx) -> Option<&str> {
        match self.entries.get(i as usize)? {
            Entry::ExtRef { name, .. } | Entry::ExtModClassRef { name, .. } => self.name(*name),
            e => self.name(e.sym_info()?.name),
        }
    }

    /// The owner entry of a symbol, if it has one.
    pub fn sym_owner(&self, i: Idx) -> Option<Idx> {
        match self.entries.get(i as usize)? {
            Entry::ExtRef { owner, .. } | Entry::ExtModClassRef { owner, .. } => *owner,
            e => Some(e.sym_info()?.owner),
        }
    }

    /// Dotted name of a symbol, walking owners up to the root.
    pub fn sym_full_name(&self, i: Idx) -> Option<String> {
        let mut parts: Vec<&str> = Vec::new();
        let mut cur = Some(i);
        let mut guard = 0;
        while let Some(c) = cur {
            guard += 1;
            if guard > 64 {
                return None;
            }
            let n = self.sym_name(c)?;
            if n == "<root>" || n == "<empty>" {
                break;
            }
            parts.push(n);
            cur = self.sym_owner(c);
        }
        parts.reverse();
        Some(parts.join("."))
    }
}

// ---------------------------------------------------------------------------
// Reader
// ---------------------------------------------------------------------------

struct Reader<'a> {
    bytes: &'a [u8],
    pos: usize,
    entry: usize,
    tag: u8,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Reader {
            bytes,
            pos: 0,
            entry: usize::MAX,
            tag: 0,
        }
    }

    fn err<T>(&self, message: impl Into<String>) -> Result<T> {
        Err(ReadError {
            entry: self.entry,
            tag: self.tag,
            offset: self.pos,
            message: message.into(),
        })
    }

    fn byte(&mut self) -> Result<u8> {
        if self.pos >= self.bytes.len() {
            return self.err("unexpected end of pickle");
        }
        let b = self.bytes[self.pos];
        self.pos += 1;
        Ok(b)
    }

    fn long_nat(&mut self) -> Result<u64> {
        let mut x: u64 = 0;
        for _ in 0..10 {
            let b = self.byte()? as u64;
            x = (x << 7) | (b & 0x7f);
            if b & 0x80 == 0 {
                return Ok(x);
            }
        }
        self.err("Nat longer than 10 bytes")
    }

    fn nat(&mut self) -> Result<u32> {
        let v = self.long_nat()?;
        if v > u32::MAX as u64 {
            return self.err(format!("Nat {v} does not fit in u32"));
        }
        Ok(v as u32)
    }

    /// nsc `readLong(len)`: signed big-endian over exactly `len` bytes.
    fn long(&mut self, len: usize) -> Result<i64> {
        if len > 8 {
            return self.err(format!("constant of {len} bytes"));
        }
        let mut x: i64 = 0;
        for _ in 0..len {
            x = (x << 8) | (self.byte()? as i64);
        }
        let leading = 64 - (len << 3);
        Ok((x << leading) >> leading)
    }
}

/// Read a complete pickle. Fails on any unknown tag or malformed body.
pub fn read_pickle(bytes: &[u8]) -> Result<Pickle> {
    let mut r = Reader::new(bytes);
    let major = r.nat()?;
    let minor = r.nat()?;
    if major != crate::pickle::MAJOR {
        return r.err(format!("unsupported pickle major version {major}"));
    }
    let nentries = r.nat()? as usize;

    // Pass 1: entry offsets and tags (needed for isSymbolRef / isNameEntry).
    let mut offsets = Vec::with_capacity(nentries);
    let mut entry_tags = Vec::with_capacity(nentries);
    let mut ends = Vec::with_capacity(nentries);
    for i in 0..nentries {
        r.entry = i;
        r.tag = 0;
        let tag = r.byte()?;
        r.tag = tag;
        let len = r.nat()? as usize;
        let start = r.pos;
        let end = match start.checked_add(len) {
            Some(e) if e <= r.bytes.len() => e,
            _ => return r.err(format!("entry length {len} overruns the pickle")),
        };
        offsets.push(start);
        entry_tags.push(tag);
        ends.push(end);
        r.pos = end;
    }

    // Pass 2: bodies.
    let mut entries = Vec::with_capacity(nentries);
    for i in 0..nentries {
        r.entry = i;
        r.tag = entry_tags[i];
        r.pos = offsets[i];
        let end = ends[i];
        let e = read_entry(&mut r, end, &entry_tags, nentries)?;
        if r.pos != end {
            return r.err(format!(
                "entry body not fully consumed ({} of {} bytes)",
                r.pos - offsets[i],
                end - offsets[i]
            ));
        }
        entries.push(e);
    }

    Ok(Pickle {
        major,
        minor,
        entries,
        entry_tags,
    })
}

fn check_ref(r: &Reader, idx: Idx, nentries: usize) -> Result<()> {
    if idx as usize >= nentries {
        return r.err(format!(
            "reference #{idx} out of range ({nentries} entries)"
        ));
    }
    Ok(())
}

fn read_ref(r: &mut Reader, nentries: usize) -> Result<Idx> {
    let i = r.nat()?;
    check_ref(r, i, nentries)?;
    Ok(i)
}

fn read_refs_until(r: &mut Reader, end: usize, nentries: usize) -> Result<Vec<Idx>> {
    let mut out = Vec::new();
    while r.pos < end {
        out.push(read_ref(r, nentries)?);
    }
    Ok(out)
}

fn is_sym_ref(all_tags: &[u8], i: Idx) -> bool {
    all_tags
        .get(i as usize)
        .is_some_and(|&t| (tags::FIRST_SYM_TAG..=tags::LAST_EXT_SYM_TAG).contains(&t))
}

fn is_name_entry(all_tags: &[u8], i: Idx) -> bool {
    matches!(
        all_tags.get(i as usize),
        Some(&tags::TERMname) | Some(&tags::TYPEname)
    )
}

fn read_sym_info(r: &mut Reader, all_tags: &[u8], nentries: usize) -> Result<SymInfo> {
    let name = read_ref(r, nentries)?;
    let owner = read_ref(r, nentries)?;
    let flags = r.long_nat()?;
    let first = read_ref(r, nentries)?;
    let (private_within, info) = if is_sym_ref(all_tags, first) {
        (Some(first), read_ref(r, nentries)?)
    } else {
        (None, first)
    };
    Ok(SymInfo {
        name,
        owner,
        flags,
        private_within,
        info,
    })
}

fn read_annot_info(
    r: &mut Reader,
    end: usize,
    all_tags: &[u8],
    nentries: usize,
) -> Result<AnnotInfo> {
    let tpe = read_ref(r, nentries)?;
    let mut args = Vec::new();
    let mut assocs = Vec::new();
    while r.pos < end {
        let a = read_ref(r, nentries)?;
        if is_name_entry(all_tags, a) {
            let v = read_ref(r, nentries)?;
            assocs.push((a, v));
        } else {
            args.push(a);
        }
    }
    Ok(AnnotInfo { tpe, args, assocs })
}

fn read_name(r: &mut Reader, end: usize) -> Result<String> {
    let raw = &r.bytes[r.pos..end];
    r.pos = end;
    // nsc writes names as UTF-8 (surrogates encoded individually, i.e. CESU-8);
    // the lossy path only matters for names outside the BMP, which the standard
    // library does not contain.
    Ok(String::from_utf8_lossy(raw).into_owned())
}

fn read_entry(r: &mut Reader, end: usize, all_tags: &[u8], n: usize) -> Result<Entry> {
    use tags as t;
    let tag = r.tag;
    let e = match tag {
        t::TERMname => Entry::TermName(read_name(r, end)?),
        t::TYPEname => Entry::TypeName(read_name(r, end)?),
        t::NONEsym => Entry::NoneSym,
        t::EXTref | t::EXTMODCLASSref => {
            let name = read_ref(r, n)?;
            let owner = if r.pos < end {
                Some(read_ref(r, n)?)
            } else {
                None
            };
            if tag == t::EXTref {
                Entry::ExtRef { name, owner }
            } else {
                Entry::ExtModClassRef { name, owner }
            }
        }
        t::TYPEsym => Entry::TypeSym(read_sym_info(r, all_tags, n)?),
        t::ALIASsym => Entry::AliasSym(read_sym_info(r, all_tags, n)?),
        t::CLASSsym => {
            let info = read_sym_info(r, all_tags, n)?;
            let this_type = if r.pos < end {
                Some(read_ref(r, n)?)
            } else {
                None
            };
            Entry::ClassSym { info, this_type }
        }
        t::MODULEsym | t::VALsym => {
            let info = read_sym_info(r, all_tags, n)?;
            let alias = if r.pos < end {
                Some(read_ref(r, n)?)
            } else {
                None
            };
            if tag == t::MODULEsym {
                Entry::ModuleSym { info, alias }
            } else {
                Entry::ValSym { info, alias }
            }
        }
        t::NOtpe => Entry::NoTpe,
        t::NOPREFIXtpe => Entry::NoPrefixTpe,
        t::THIStpe => Entry::ThisTpe(read_ref(r, n)?),
        t::SINGLEtpe => {
            let prefix = read_ref(r, n)?;
            let sym = read_ref(r, n)?;
            Entry::SingleTpe { prefix, sym }
        }
        t::SUPERtpe => {
            let this_tpe = read_ref(r, n)?;
            let super_tpe = read_ref(r, n)?;
            Entry::SuperTpe {
                this_tpe,
                super_tpe,
            }
        }
        t::CONSTANTtpe => Entry::ConstantTpe(read_ref(r, n)?),
        t::TYPEREFtpe => {
            let prefix = read_ref(r, n)?;
            let sym = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Entry::TypeRefTpe { prefix, sym, args }
        }
        t::TYPEBOUNDStpe => {
            let lo = read_ref(r, n)?;
            let hi = read_ref(r, n)?;
            Entry::TypeBoundsTpe { lo, hi }
        }
        t::REFINEDtpe => {
            let sym = read_ref(r, n)?;
            let parents = read_refs_until(r, end, n)?;
            Entry::RefinedTpe { sym, parents }
        }
        t::CLASSINFOtpe => {
            let sym = read_ref(r, n)?;
            let parents = read_refs_until(r, end, n)?;
            Entry::ClassInfoTpe { sym, parents }
        }
        t::METHODtpe | t::IMPLICITMETHODtpe => {
            let result = read_ref(r, n)?;
            let params = read_refs_until(r, end, n)?;
            if tag == t::METHODtpe {
                Entry::MethodTpe { result, params }
            } else {
                Entry::ImplicitMethodTpe { result, params }
            }
        }
        t::POLYtpe => {
            let result = read_ref(r, n)?;
            let tparams = read_refs_until(r, end, n)?;
            Entry::PolyTpe { result, tparams }
        }
        t::EXISTENTIALtpe => {
            let result = read_ref(r, n)?;
            let quantified = read_refs_until(r, end, n)?;
            Entry::ExistentialTpe { result, quantified }
        }
        t::ANNOTATEDtpe => {
            let tpe = read_ref(r, n)?;
            let annots = read_refs_until(r, end, n)?;
            Entry::AnnotatedTpe { tpe, annots }
        }
        t::DEBRUIJNINDEXtpe => {
            let level = r.nat()?;
            let index = r.nat()?;
            Entry::DeBruijnIndexTpe { level, index }
        }
        t::LITERALunit => Entry::Literal(Constant::Unit),
        t::LITERALboolean => Entry::Literal(Constant::Boolean(r.long(end - r.pos)? != 0)),
        t::LITERALbyte => Entry::Literal(Constant::Byte(r.long(end - r.pos)? as i8)),
        t::LITERALshort => Entry::Literal(Constant::Short(r.long(end - r.pos)? as i16)),
        t::LITERALchar => Entry::Literal(Constant::Char(r.long(end - r.pos)? as u32 & 0xffff)),
        t::LITERALint => Entry::Literal(Constant::Int(r.long(end - r.pos)? as i32)),
        t::LITERALlong => Entry::Literal(Constant::Long(r.long(end - r.pos)?)),
        t::LITERALfloat => {
            Entry::Literal(Constant::Float(f32::from_bits(r.long(end - r.pos)? as u32)))
        }
        t::LITERALdouble => Entry::Literal(Constant::Double(f64::from_bits(
            r.long(end - r.pos)? as u64
        ))),
        t::LITERALstring => Entry::Literal(Constant::Str(read_ref(r, n)?)),
        t::LITERALnull => Entry::Literal(Constant::Null),
        t::LITERALclass => Entry::Literal(Constant::Class(read_ref(r, n)?)),
        t::LITERALenum => Entry::Literal(Constant::Enum(read_ref(r, n)?)),
        t::LITERALsymbol => Entry::Literal(Constant::Symbol(read_ref(r, n)?)),
        t::SYMANNOT => {
            let sym = read_ref(r, n)?;
            let annot = read_annot_info(r, end, all_tags, n)?;
            Entry::SymAnnot { sym, annot }
        }
        t::ANNOTINFO => Entry::AnnotInfo(read_annot_info(r, end, all_tags, n)?),
        t::ANNOTARGARRAY => Entry::AnnotArgArray(read_refs_until(r, end, n)?),
        t::CHILDREN => {
            let sym = read_ref(r, n)?;
            let children = read_refs_until(r, end, n)?;
            Entry::Children { sym, children }
        }
        t::MODIFIERS => {
            let hi = r.nat()? as u64;
            let lo = r.nat()? as u64;
            let private_within = read_ref(r, n)?;
            Entry::Modifiers {
                flags: (hi << 32) | lo,
                private_within,
            }
        }
        t::TREE => read_tree_entry(r, end, n)?,
        _ => return r.err(format!("unknown pickle tag {tag}")),
    };
    Ok(e)
}

fn read_tree_entry(r: &mut Reader, end: usize, n: usize) -> Result<Entry> {
    use tags as t;
    let tt = r.byte()?;
    let tpe = if tt == t::EMPTYtree {
        None
    } else {
        Some(read_ref(r, n)?)
    };
    // `setSymModsName` order: symbol, modifiers, name.
    macro_rules! smn {
        () => {{
            let s = read_ref(r, n)?;
            let m = read_ref(r, n)?;
            let nm = read_ref(r, n)?;
            (s, m, nm)
        }};
    }
    let tree = match tt {
        t::EMPTYtree => Tree::Empty,
        t::PACKAGEtree => {
            let (sym, mods, name) = smn!();
            let pid = read_ref(r, n)?;
            let stats = read_refs_until(r, end, n)?;
            Tree::PackageDef {
                sym,
                mods,
                name,
                pid,
                stats,
            }
        }
        t::CLASStree => {
            let (sym, mods, name) = smn!();
            let template = read_ref(r, n)?;
            let tparams = read_refs_until(r, end, n)?;
            Tree::ClassDef {
                sym,
                mods,
                name,
                template,
                tparams,
            }
        }
        t::MODULEtree => {
            let (sym, mods, name) = smn!();
            let template = read_ref(r, n)?;
            Tree::ModuleDef {
                sym,
                mods,
                name,
                template,
            }
        }
        t::VALDEFtree => {
            let (sym, mods, name) = smn!();
            let tpt = read_ref(r, n)?;
            let rhs = read_ref(r, n)?;
            Tree::ValDef {
                sym,
                mods,
                name,
                tpt,
                rhs,
            }
        }
        t::DEFDEFtree => {
            let (sym, mods, name) = smn!();
            let ntp = r.nat()? as usize;
            let mut tparams = Vec::with_capacity(ntp);
            for _ in 0..ntp {
                tparams.push(read_ref(r, n)?);
            }
            let nss = r.nat()? as usize;
            let mut vparamss = Vec::with_capacity(nss);
            for _ in 0..nss {
                let np = r.nat()? as usize;
                let mut ps = Vec::with_capacity(np);
                for _ in 0..np {
                    ps.push(read_ref(r, n)?);
                }
                vparamss.push(ps);
            }
            let tpt = read_ref(r, n)?;
            let rhs = read_ref(r, n)?;
            Tree::DefDef {
                sym,
                mods,
                name,
                tparams,
                vparamss,
                tpt,
                rhs,
            }
        }
        t::TYPEDEFtree => {
            let (sym, mods, name) = smn!();
            let rhs = read_ref(r, n)?;
            let tparams = read_refs_until(r, end, n)?;
            Tree::TypeDef {
                sym,
                mods,
                name,
                rhs,
                tparams,
            }
        }
        t::LABELtree => {
            let sym = read_ref(r, n)?;
            let name = read_ref(r, n)?;
            let rhs = read_ref(r, n)?;
            let params = read_refs_until(r, end, n)?;
            Tree::LabelDef {
                sym,
                name,
                rhs,
                params,
            }
        }
        t::IMPORTtree => {
            let sym = read_ref(r, n)?;
            let expr = read_ref(r, n)?;
            let mut selectors = Vec::new();
            while r.pos < end {
                let from = read_ref(r, n)?;
                let to = read_ref(r, n)?;
                selectors.push(ImportSelector { from, to });
            }
            Tree::Import {
                sym,
                expr,
                selectors,
            }
        }
        t::DOCDEFtree => {
            let comment = read_ref(r, n)?;
            let definition = read_ref(r, n)?;
            Tree::DocDef {
                comment,
                definition,
            }
        }
        t::TEMPLATEtree => {
            let sym = read_ref(r, n)?;
            let np = r.nat()? as usize;
            let mut parents = Vec::with_capacity(np);
            for _ in 0..np {
                parents.push(read_ref(r, n)?);
            }
            let self_ = read_ref(r, n)?;
            let body = read_refs_until(r, end, n)?;
            Tree::Template {
                sym,
                parents,
                self_,
                body,
            }
        }
        t::BLOCKtree => {
            let expr = read_ref(r, n)?;
            let stats = read_refs_until(r, end, n)?;
            Tree::Block { expr, stats }
        }
        t::CASEtree => {
            let pat = read_ref(r, n)?;
            let guard = read_ref(r, n)?;
            let body = read_ref(r, n)?;
            Tree::CaseDef { pat, guard, body }
        }
        t::ALTERNATIVEtree => Tree::Alternative(read_refs_until(r, end, n)?),
        t::STARtree => Tree::Star(read_ref(r, n)?),
        t::BINDtree => {
            let sym = read_ref(r, n)?;
            let name = read_ref(r, n)?;
            let body = read_ref(r, n)?;
            Tree::Bind { sym, name, body }
        }
        t::UNAPPLYtree => {
            let fun = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Tree::UnApply { fun, args }
        }
        t::ARRAYVALUEtree => {
            let elemtpt = read_ref(r, n)?;
            let elems = read_refs_until(r, end, n)?;
            Tree::ArrayValue { elemtpt, elems }
        }
        t::FUNCTIONtree => {
            let sym = read_ref(r, n)?;
            let body = read_ref(r, n)?;
            let vparams = read_refs_until(r, end, n)?;
            Tree::Function { sym, body, vparams }
        }
        t::ASSIGNtree => {
            let lhs = read_ref(r, n)?;
            let rhs = read_ref(r, n)?;
            Tree::Assign { lhs, rhs }
        }
        t::IFtree => {
            let cond = read_ref(r, n)?;
            let thenp = read_ref(r, n)?;
            let elsep = read_ref(r, n)?;
            Tree::If { cond, thenp, elsep }
        }
        t::MATCHtree => {
            let selector = read_ref(r, n)?;
            let cases = read_refs_until(r, end, n)?;
            Tree::Match { selector, cases }
        }
        t::RETURNtree => {
            let sym = read_ref(r, n)?;
            let expr = read_ref(r, n)?;
            Tree::Return { sym, expr }
        }
        t::TREtree => {
            let block = read_ref(r, n)?;
            let finalizer = read_ref(r, n)?;
            let catches = read_refs_until(r, end, n)?;
            Tree::Try {
                block,
                finalizer,
                catches,
            }
        }
        t::THROWtree => Tree::Throw(read_ref(r, n)?),
        t::NEWtree => Tree::New(read_ref(r, n)?),
        t::TYPEDtree => {
            let expr = read_ref(r, n)?;
            let tpt = read_ref(r, n)?;
            Tree::Typed { expr, tpt }
        }
        t::TYPEAPPLYtree => {
            let fun = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Tree::TypeApply { fun, args }
        }
        t::APPLYtree => {
            let fun = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Tree::Apply { fun, args }
        }
        t::APPLYDYNAMICtree => {
            let sym = read_ref(r, n)?;
            let fun = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Tree::ApplyDynamic { sym, fun, args }
        }
        t::SUPERtree => {
            let sym = read_ref(r, n)?;
            let qual = read_ref(r, n)?;
            let mix = read_ref(r, n)?;
            Tree::Super { sym, qual, mix }
        }
        t::THIStree => {
            let sym = read_ref(r, n)?;
            let qual = read_ref(r, n)?;
            Tree::This { sym, qual }
        }
        t::SELECTtree => {
            let sym = read_ref(r, n)?;
            let qualifier = read_ref(r, n)?;
            let selector = read_ref(r, n)?;
            Tree::Select {
                sym,
                qualifier,
                selector,
            }
        }
        t::IDENTtree => {
            let sym = read_ref(r, n)?;
            let name = read_ref(r, n)?;
            Tree::Ident { sym, name }
        }
        t::LITERALtree => Tree::Literal(read_ref(r, n)?),
        t::TYPEtree => Tree::TypeTree,
        t::ANNOTATEDtree => {
            let annot = read_ref(r, n)?;
            let arg = read_ref(r, n)?;
            Tree::Annotated { annot, arg }
        }
        t::SINGLETONTYPEtree => Tree::SingletonTypeTree(read_ref(r, n)?),
        t::SELECTFROMTYPEtree => {
            let qualifier = read_ref(r, n)?;
            let selector = read_ref(r, n)?;
            Tree::SelectFromTypeTree {
                qualifier,
                selector,
            }
        }
        t::COMPOUNDTYPEtree => Tree::CompoundTypeTree(read_ref(r, n)?),
        t::APPLIEDTYPEtree => {
            let tpt = read_ref(r, n)?;
            let args = read_refs_until(r, end, n)?;
            Tree::AppliedTypeTree { tpt, args }
        }
        t::TYPEBOUNDStree => {
            let lo = read_ref(r, n)?;
            let hi = read_ref(r, n)?;
            Tree::TypeBoundsTree { lo, hi }
        }
        t::EXISTENTIALTYPEtree => {
            let tpt = read_ref(r, n)?;
            let where_clauses = read_refs_until(r, end, n)?;
            Tree::ExistentialTypeTree { tpt, where_clauses }
        }
        _ => return r.err(format!("unknown tree tag {tt}")),
    };
    Ok(Entry::Tree { tpe, tree })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pickle;

    #[test]
    fn tag_table_matches_the_writer() {
        assert_eq!(tags::TERMname, pickle::TERMNAME);
        assert_eq!(tags::TYPEname, pickle::TYPENAME);
        assert_eq!(tags::NONEsym, pickle::NONESYM);
        assert_eq!(tags::TYPEsym, pickle::TYPESYM);
        assert_eq!(tags::ALIASsym, pickle::ALIASSYM);
        assert_eq!(tags::CLASSsym, pickle::CLASSSYM);
        assert_eq!(tags::MODULEsym, pickle::MODULESYM);
        assert_eq!(tags::VALsym, pickle::VALSYM);
        assert_eq!(tags::EXTref, pickle::EXTREF);
        assert_eq!(tags::EXTMODCLASSref, pickle::EXTMODCLASSREF);
        assert_eq!(tags::NOtpe, pickle::NOTPE);
        assert_eq!(tags::NOPREFIXtpe, pickle::NOPREFIXTPE);
        assert_eq!(tags::THIStpe, pickle::THISTPE);
        assert_eq!(tags::SINGLEtpe, pickle::SINGLETPE);
        assert_eq!(tags::CONSTANTtpe, pickle::CONSTANTtpe);
        assert_eq!(tags::TYPEREFtpe, pickle::TYPEREFTPE);
        assert_eq!(tags::TYPEBOUNDStpe, pickle::TYPEBOUNDSTPE);
        assert_eq!(tags::REFINEDtpe, pickle::REFINEDTPE);
        assert_eq!(tags::CLASSINFOtpe, pickle::CLASSINFOTPE);
        assert_eq!(tags::METHODtpe, pickle::METHODTPE);
        assert_eq!(tags::POLYtpe, pickle::POLYTPE);
        assert_eq!(tags::LITERALunit, pickle::LITERALunit);
        assert_eq!(tags::LITERALstring, pickle::LITERALstring);
        assert_eq!(tags::LITERALclass, pickle::LITERALclass);
        assert_eq!(tags::SYMANNOT, pickle::SYMANNOT);
        assert_eq!(tags::ANNOTATEDtpe, pickle::ANNOTATEDTPE);
        assert_eq!(tags::ANNOTINFO, pickle::ANNOTINFO);
        assert_eq!(tags::EXISTENTIALtpe, pickle::EXISTENTIALTPE);
        assert_eq!(tags::TREE, pickle::TREE);
        assert_eq!(tags::APPLYtree, pickle::APPLYtree);
        assert_eq!(tags::SELECTtree, pickle::SELECTtree);
        assert_eq!(tags::IDENTtree, pickle::IDENTtree);
        assert_eq!(tags::LITERALtree, pickle::LITERALtree);
        assert_eq!(tags::THIStree, pickle::THIStree);
        assert_eq!(tags::SUPERtree, pickle::SUPERtree);
        assert_eq!(tags::TYPEAPPLYtree, pickle::TYPEAPPLYtree);
    }

    #[test]
    fn unknown_tag_is_an_error_not_a_skip() {
        // major, minor, nentries=1, tag=99, len=0
        let bytes = [5u8, 2, 1, 99, 0];
        let err = read_pickle(&bytes).unwrap_err();
        assert_eq!(err.tag, 99);
        assert!(err.message.contains("unknown pickle tag 99"), "{err}");
    }

    #[test]
    fn truncated_entry_is_an_error() {
        let bytes = [5u8, 2, 1, 1, 40];
        let err = read_pickle(&bytes).unwrap_err();
        assert!(err.message.contains("overruns"), "{err}");
    }

    #[test]
    fn reads_pickles_written_by_our_own_writer() {
        // Covers CLASSsym / MODULEsym / VALsym / TYPEsym / ALIASsym, POLYtpe,
        // METHODtpe, TYPEREFtpe, EXISTENTIALtpe, REFINEDtpe, CONSTANTtpe,
        // ANNOTATEDtpe and SYMANNOT through the writer we already have.
        let src = r#"
trait Show { def show: String }
trait Named { def name: String }
class Box[A](val get: A) {
  type Elem = A
  def map[B](f: A => B): Box[B] = new Box(f(get))
  def raw(xs: List[_]): Int = 0
  def both: Show with Named = null
  def self0: this.type = this
}
case class Point(x: Int, y: Int)
object Lib {
  type Alias = String
  val n: Int = 1
  @deprecated("gone", "2.13.0") def old(s: String): String = s
  def lit(x: 1): Int = 0
}
"#;
        let (_t, st, diags) = scala_rs_typer::typecheck_str(src);
        assert!(
            !scala_rs_typer::has_errors(&diags),
            "type errors: {:?}",
            diags.iter().map(|d| &d.message).collect::<Vec<_>>()
        );
        let pickles = pickle::pickle_all(&st);
        assert!(!pickles.is_empty(), "expected pickles");
        let mut seen_class = false;
        let mut seen_alias = false;
        for raw in pickles.values() {
            // Go through the annotation-string encoding, like a real classfile.
            let enc = pickle::encode_to_annotation_string(raw);
            let dec = pickle::decode_annotation_string(&enc);
            let p = read_pickle(&dec).unwrap_or_else(|e| panic!("our own pickle: {e}"));
            assert_eq!(p.major, pickle::MAJOR);
            for e in &p.entries {
                match e {
                    Entry::ClassSym { info, .. } if p.name(info.name) == Some("Box") => {
                        seen_class = true;
                    }
                    Entry::AliasSym(info) if p.name(info.name) == Some("Alias") => {
                        seen_alias = true;
                    }
                    _ => {}
                }
            }
        }
        assert!(seen_class, "Box CLASSsym not read back");
        assert!(seen_alias, "Lib.Alias ALIASsym not read back");
    }
}
