// Numbers: Int/Long/Double mixed in one expression, overflow, division and
// modulo signs, and how each prints.
object Main {
  def main(args: Array[String]): Unit = {
    val i = 7; val l = 7L; val d = 7.0; val f = 7.0f; val s: Short = 7; val b: Byte = 7
    println(i + l)
    println(i + d)
    println(l * d)
    println(i / 2)
    println(i / 2.0)
    println(l / 2)
    println(-7 / 2)
    println(-7 % 3)
    println(7 % -3)
    println(-7L / 2L)
    println(Int.MaxValue + 1)
    println(Int.MinValue - 1)
    println(Int.MaxValue.toLong + 1L)
    println(Long.MaxValue + 1L)
    println(Int.MaxValue * 2)
    println((Int.MaxValue * 2).toLong)
    println(Int.MaxValue.toDouble + 1)
    println(1 << 31)
    println(1L << 63)
    println(-8 >> 1)
    println(-8 >>> 1)
    println(-8L >>> 1)
    println(0.1 + 0.2)
    println(1.0 / 3.0)
    println(1.0f / 3.0f)
    println((1.0 / 3.0).toFloat)
    println(1e20)
    println(1e-7)
    println(100000000.0)
    println(1.0E7)
    println(0.0001)
    println(1.0 / 0.0)
    println(-1.0 / 0.0)
    println(0.0 / 0.0)
    println(-0.0)
    println(math.abs(-0.0))
    println(Double.NaN == Double.NaN)
    println(Double.NaN != Double.NaN)
    println(2.5.round); println(3.5.round); println((-2.5).round)
    println(2.5.toInt); println((-2.5).toInt)
    println(1e19.toLong); println(1e19.toInt)
    println(Double.NaN.toInt)
    println((s + b).getClass.toString)
    println(s * 1000000)
    println(b.toChar)
    println('a' + 1)
    println(('a' + 1).toChar)
    println(f + d)
    println(3.0f.toString)
    println(java.lang.Long.toBinaryString(-8L))
    println(math.max(1, 2L))
    println(math.pow(2, 10))
    println(List(1, 2L, 3.0).map(_.toString))
    println(BigInt(2).pow(70))
    println(1.toString + 1L.toString + 1.0.toString + 1.0f.toString)
    var acc = 0L
    var k = 0
    while (k < 5) { acc = acc * 10 + k; k += 1 }
    println(acc)
  }
}
